#!/usr/bin/python
################################################################################
# AGENT LOOKUP COMMAND LINE INTERFACE
#
# Justin Dierking
# phnomcobra@gmail.com
#
# 05/26/2018 Original construction
################################################################################

import argparse

from stembot.agentint import Console

parser = argparse.ArgumentParser(description = 'agent lookup command line interface')

parser.add_argument('subject', action = 'store')
parser.add_argument('-n', '--not', dest = 'not', action = 'store_true')

object_group = parser.add_mutually_exclusive_group()

object_group.add_argument('-t', '--tags', dest = 'tags', action = 'store_true')
object_group.add_argument('-c', '--command', dest = 'command', action = 'store')
object_group.add_argument('-f', '--file', dest = 'file', action = 'store')
object_group.add_argument('-k', '--key-val', dest = 'key_name', action = 'store')
object_group.add_argument('-F', '--function', dest = 'function', action = 'store')

kargs = vars(parser.parse_args())

if kargs['command'] != None:
    results = Console().Cascade().system(kargs['command'])
elif kargs['file'] != None:
    results = Console().Cascade().file_read(kargs['file'])
elif kargs['function'] != None:
    results = Console().Cascade().run_function_by_name(kargs['function'])
elif kargs['tags']:
    results = {}

    for tag in Console().AGTCollections('tags').find():
        if tag.agtuuid not in results:
            results[tag.agtuuid] = []
        
        if 'value' in tag.object:
            results[tag.agtuuid].append(str(tag.object['value']))
elif kargs['key_name'] != None:
    results = {}

    for key in Console().AGTCollections('kvstore').find(name = kargs['key_name']):
        if key.agtuuid not in results:
            results[key.agtuuid] = []
        
        if 'value' in key.object:
            results[key.agtuuid].append(str(key.object['value']))

if kargs['not']:
    for agtuuid, result in results.iteritems():
        if kargs['subject'] not in result:
            print agtuuid
else:            
    for agtuuid, result in results.iteritems():
        if kargs['subject'] in result:
            print agtuuid