#!/usr/bin/python
################################################################################
# PEER COMMAND LINE INTERFACE
#
# Justin Dierking
# justin.l.dierking.civ@mail.mil
# (614) 692 2050
#
# 05/20/2018 Original construction
################################################################################

import argparse
import json

from stembot.agentint import Console

parser = argparse.ArgumentParser(description = 'peer command line interface')

subparsers = parser.add_subparsers(help = 'commands')

set_parser = subparsers.add_parser('set', help = 'set peer')
set_parser.add_argument('--ttl', dest = 'ttl', action = 'store', help = 'time-to-live (seconds)', type = int)
set_parser.add_argument('-p', dest = 'polling', action = 'store_true', help = 'enable polling')
set_parser.add_argument('peer_url', action = 'store', help = 'url')

del_parser = subparsers.add_parser('del', help = 'delete peer')
del_parser.add_argument('--all', dest = 'del_all_agents', action = 'store_true')
del_parser.add_argument('--agtuuid', dest = 'del_agtuuid', action = 'store')

list_parser = subparsers.add_parser('list')
list_parser.add_argument('-p', dest = 'list_peers', action = 'store_true', help = 'list peers')
list_parser.add_argument('-r', dest = 'list_routes', action = 'store_true', help = 'list routes')
list_parser.add_argument('-c', dest = 'list_counters', action = 'store_true', help = 'list counters')

kargs = vars(parser.parse_args())

if 'peer_url' in kargs:
    if kargs['ttl'] == None:
        Console().set_peer(kargs['peer_url'], \
                           polling = kargs['polling'])
    else:
        Console().set_peer(kargs['peer_url'], \
                           polling = kargs['polling'], \
                           ttl = kargs['ttl'])

if 'del_all_agents' in kargs:
    if kargs['del_all_agents']:
        Console().delete_peers()

if 'del_agtuuid' in kargs:
    Console().delete_peer(kargs['del_agtuuid'])

if 'list_peers' in kargs:
    if kargs['list_peers']:
        print json.dumps(Console().get_peers(), indent = 4)

if 'list_routes' in kargs:
    if kargs['list_routes']:
        print json.dumps(Console().get_routes(), indent = 4)

if 'list_counters' in kargs:
    if kargs['list_counters']:
        print json.dumps(Console().get_counters(), indent = 4, sort_keys = True)        