#!/usr/bin/python
################################################################################
# MAIN
#
# Justin Dierking
# justin.l.dierking.civ@mail.mil
# (614) 692 2050
#
# 07/18/2017 Original construction
################################################################################

if __name__ == "__main__":
    import cherrypy
    import os
    import hashlib
        
    from stembot import kvstore
    from stembot.utils import sucky_uuid
    from stembot.root import Root

    current_dir = os.path.dirname(os.path.abspath(__file__))
            
    config = {
        'agtuuid': kvstore.get(name = "agtuuid", default = sucky_uuid()),
        'log.screen': False,
        #'server.thread_pool' : kvstore.get(name = "thread_pool", default = 100),
        'server.socket_host' : kvstore.get(name = "socket_host", default = '0.0.0.0'),
        'server.socket_port' : kvstore.get(name = "socket_port", default = 53443),
        #'server.socket_timeout' : kvstore.get(name = "socket_timeout", default = 90),
        'server.ssl_module' : 'builtin',
        'server.ssl_certificate' : os.path.join(current_dir, './cert.pem'),
        'server.ssl_private_key' : os.path.join(current_dir, './privkey.pem'),
        'server.secret_digest' : kvstore.get(name = "secret_digest", default = hashlib.sha256("changeme").hexdigest()),
    }
    
    cherrypy.config.update(config)
            
    cherrypy.quickstart(Root())