#!/usr/bin/python
################################################################################
# TAGGING COMMAND LINE INTERFACE
#
# Justin Dierking
# justin.l.dierking.civ@mail.mil
# (614) 692 2050
#
# 06/01/2018 Original construction
################################################################################

import argparse

from stembot.tagging import get_tag_values, \
                            set_tag_value, \
                            del_tag_value

parser = argparse.ArgumentParser(description = 'tagging interface')

subparsers = parser.add_subparsers(help = 'commands')

set_parser = subparsers.add_parser('set', help = 'set tag')
set_parser.add_argument('set_tag_value', action = 'store')

del_parser = subparsers.add_parser('del', help = 'delete tag')
del_parser.add_argument('del_tag_value', action = 'store')

get_parser = subparsers.add_parser('get', help = 'list tags')

kargs = vars(parser.parse_args())

if 'set_tag_value' in kargs:
    set_tag_value(kargs['set_tag_value'])
elif 'del_tag_value' in kargs:
    del_tag_value(kargs['del_tag_value'])

for value in get_tag_values():
    print value
