#!/usr/bin/python

from stembot.document import Collection

def execute(event, context):
    collection = Collection(event["collection name"])
    
    results = []
        
    for objuuid in collection.find_objuuids(**event["query"]):
        results.append(collection.get_object(objuuid).object)
    
    return results